# sample configuration for iptables service
# you can edit this manually or use system-config-firewall
# please do not ask us to add additional ports/services to this default configuration
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p all -m state --state ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -p all -m state --state ESTABLISHED,RELATED -j ACCEPT
-A FORWARD -p all -m state --state ESTABLISHED,RELATED -j ACCEPT
-A FORWARD -i enp3s7 -j ACCEPT
-A INPUT -p udp -m state --state NEW -m udp --dport 15333 -j ACCEPT
-A INPUT -p tcp -s 77.41.142.206 --dport 32523 -j ACCEPT
-A INPUT -p tcp --dport 32523 -j DROP
COMMIT
# Completed on Wed Jul  3 13:28:35 2019
# Generated by iptables-save v1.4.21 on Wed Jul  3 13:28:35 2019
*nat
:PREROUTING ACCEPT [156:8757]
:INPUT ACCEPT [2:305]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o enp2s0 -j MASQUERADE
#-A POSTROUTING -s 192.168.20.0/24 -o enp3s7 -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 -o enp3s7 -j MASQUERADE
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33006 -j DNAT --to-destination 10.0.1.57:3389
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33007 -j DNAT --to-destination 10.0.1.2:3389
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33008 -j DNAT --to-destination 10.0.1.30:3389
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33009 -j DNAT --to-destination 10.0.1.16:3389
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33010 -j DNAT --to-destination 10.0.1.35:3389
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33011 -j DNAT --to-destination 10.0.1.129:3389
-A PREROUTING -i enp2s0 -p tcp -m tcp --dport 33012 -j DNAT --to-destination 10.0.1.121:3389
-A PREROUTING -s 77.41.142.206 -p tcp -m tcp --dport 37525 -j DNAT --to-destination 10.0.1.57:10050
-A PREROUTING -s 77.41.142.206 -p tcp -m tcp --dport 37524 -j DNAT --to-destination 10.0.1.2:10050
COMMIT
# Completed on Wed Jul  3 13:28:35 2019
# Generated by iptables-save v1.4.21 on Wed Jul  3 13:28:35 2019
*mangle
:PREROUTING ACCEPT [8210:2069072]
:INPUT ACCEPT [2400:194525]
:FORWARD ACCEPT [5618:1862378]
                                    
